# Generated by Django 4.2.3 on 2023-07-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='edghamPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_link', models.SlugField(unique=True)),
                ('prev_fisrt_product_price', models.FloatField()),
                ('fisrt_product_price', models.FloatField()),
                ('prev_my_product_price', models.FloatField()),
                ('my_product_price', models.FloatField()),
                ('prev_my_product_rank', models.FloatField()),
                ('my_product_rank', models.FloatField()),
            ],
        ),
    ]
