# Generated by Django 4.2.3 on 2023-07-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edqam_page_scrapper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='edghamPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_link', models.SlugField(unique=True)),
                ('prev_fisrt_product_price', models.FloatField()),
                ('fisrt_product_price', models.FloatField()),
                ('prev_my_product_price', models.IntegerField()),
                ('my_product_price', models.IntegerField()),
                ('prev_my_product_rank', models.IntegerField()),
                ('my_product_rank', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='edghamPageModel',
        ),
    ]
