# Generated by Django 4.2.3 on 2023-07-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edqam_page_scrapper', '0002_edghampage_delete_edghampagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edghampage',
            name='fisrt_product_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edghampage',
            name='my_product_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edghampage',
            name='my_product_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edghampage',
            name='prev_fisrt_product_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edghampage',
            name='prev_my_product_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edghampage',
            name='prev_my_product_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
