# Generated by Django 4.2.1 on 2023-07-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edqam_page_scrapper', '0003_alter_edghampage_fisrt_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edghampage',
            name='prev_second_product_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edghampage',
            name='second_product_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
