# Generated by Django 4.2.1 on 2023-07-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edqam_page_scrapper', '0004_edghampage_prev_second_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edghampage',
            name='my_product_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edghampage',
            name='prev_my_product_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
