# Generated by Django 4.2.1 on 2023-07-16 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edqam_page_scrapper', '0005_alter_edghampage_my_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edghampage',
            name='is_your_product_on_this_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='edghampage',
            name='store_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='store_edghamPage', to=settings.AUTH_USER_MODEL),
        ),
    ]
