# Generated by Django 4.2.1 on 2023-07-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edqam_page_scrapper', '0006_edghampage_is_your_product_on_this_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edghampage',
            name='page_link',
            field=models.URLField(max_length=400),
        ),
    ]
