# Generated by Django 4.2.1 on 2023-07-16 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edqam_page_scrapper', '0008_alter_edghampage_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='edghampage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edghampage',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
