# Generated by Django 4.2.3 on 2023-07-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edqam_page_scrapper', '0010_alter_edghampage_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edghampage',
            name='product_name',
            field=models.CharField(default='lotus', max_length=256),
            preserve_default=False,
        ),
    ]
